skyderby/skyderby

- config/locales/es.yml
- config/locales/models/track_videos.es.yml
- config/locales/models/tracks.es.yml
- config/locales/views/charts/all_data_chart.es.yml
- config/locales/views/charts/elev_chart.es.yml
- config/locales/views/charts/gr_chart.es.yml
- config/locales/views/charts/spd_chart.es.yml
- config/locales/views/track_videos/edit.es.yml
- config/locales/views/track_videos/form.es.yml
- config/locales/views/track_videos/new.es.yml
- config/locales/views/tracks/choose.es.yml
- config/locales/views/tracks/edit.es.yml
- config/locales/views/tracks/form.es.yml
- config/locales/views/tracks/index.es.yml
- config/locales/views/tracks/replay.es.yml
Spanish translations from issue #47
> Translations for issue #47

- Gemfile
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/mobile/pages/tracks/_track_item.scss
- app/helpers/tracks_helper.rb
- app/views/manage/missing_places/index.html.haml
- app/views/suits/index.js.erb
- app/views/tracks/_track.html+mobile.haml
- app/views/tracks/_track.html.haml
- app/views/tracks/index.html+mobile.haml
- app/views/tracks/index.html.haml
- app/views/tracks/index.js.erb
- app/views/tracks/show.js+mobile.erb
- app/views/tracks/show.js.erb
- app/views/virtual_competitions/show.js.erb
New design for track list by @skreets
```
window.history.replaceState({ turbolinks: {} }, ...)
```
found on: https://github.com/turbolinks/turbolinks/issues/219
> Track list for mobile devices

- app/assets/javascripts/app/views/flight_profiles.js.coffee
- app/controllers/api/v1/places/exit_measurements_controller.rb
- app/controllers/places/select_options_controller.rb
- app/controllers/places_controller.rb
- app/models/exit_measurement.rb
- app/models/place.rb
- app/models/place_line.rb
- app/views/api/v1/places/exit_measurements/index.json.jbuilder
- app/views/places/_form.html.haml
- app/views/places/edit.html.haml
- app/views/places/form/_exit_measurement_fields.html.haml
- app/views/places/form/_exit_measurements.html.haml
- app/views/places/form/_exit_measurements_template.html.haml
- app/views/places/form/_place_line.html.haml
- app/views/places/form/_place_line_fields.html.haml
- app/views/places/form/_place_line_template.html.haml
- config/routes.rb
- db/migrate/20180219081813_create_place_lines.rb
- db/schema.rb
related issue: #86 
This PR resolve this issue.
What's left:
> Places: Exit measurements per line

- app/controllers/track_files/tracks_controller.rb
- app/controllers/track_files_controller.rb
- app/models/concerns/ownerable.rb
- app/models/event_track.rb
- app/models/profile.rb
- app/models/qualification_jump.rb
- app/models/track.rb
- app/models/user.rb
- app/policies/track_policy.rb
- app/services/create_track_service.rb
- db/migrate/20180226070838_add_owner_to_tracks.rb
- db/schema.rb
- spec/controllers/tracks_controller_spec.rb
- spec/factories/points.rb
- spec/factories/tracks.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/services/create_track_service/data_frequency_detector_spec.rb
- spec/services/create_track_service/missing_ranges_detector_spec.rb
- spec/support/create_track_helper.rb
- spec/system/competitions/scoring_spec.rb
- spec/system/events_spec.rb
- spec/system/online_competitions_scoring_spec.rb
- spec/system/wbr_scoring_spec.rb
Goal for this PR is to create flexible permission policy with following rules:
1. If track was uploaded by user (registered or guest user) - user has all permissions over it
2. if track was uploaded by registered user, but later chosen as a result in competition - user has all permissions except to delete this track
3. if track was uploaded during competition (PPC-like, Hungary boogie, WBR tournament) user do not have any permissions over this track, but organizer of event does.
Whats left for main goal - setting owner for track during uploading.
> Permissions for track

- app/models/event.rb
- app/models/event_track.rb
- app/models/round.rb
- app/views/events/event_tracks/_show_modal.html.haml
- app/views/events/scoreboards/_hungary_boogie.html.haml
- app/views/events/scoreboards/_speed_distance_time.html.haml
- db/migrate/20180224104950_change_round_name_to_round_number.rb
- db/schema.rb
- spec/models/round_spec.rb
> Correct ordering rounds if its more than 9

- Gemfile
- Gemfile.lock
- app/controllers/events/scoreboards_controller.rb
- app/views/events/scoreboards/_hungary_boogie.xlsx.axlsx
- app/views/events/scoreboards/_speed_distance_time.xlsx.axlsx
- app/views/events/scoreboards/show.xlsx.axlsx
- app/views/events/show.html.haml
The feature every competition organizer requested this year
> Export to Excel

- app/assets/stylesheets/mobile/_pagingation.scss
- app/assets/stylesheets/mobile/pages/_online_competition.scss
- app/assets/stylesheets/mobile/pages/_online_competitions_index.scss
- app/views/virtual_competitions/_navbar.html.haml
- app/views/virtual_competitions/_scoreboard.html+mobile.haml
- app/views/virtual_competitions/_scoreboard.html.haml
- app/views/virtual_competitions/show.html+mobile.haml
- app/views/virtual_competitions/show.html.haml
- app/views/virtual_competitions/show.js.erb
* Added navbar: Overall / 2015 / 2016 / etc
* Added pagination.
* Changed font to proxima nova.
* Removed unnecessary margin on top
> Improvements to online competitions on mobile

- app/assets/stylesheets/events/rounds/_map.scss
- app/javascript/controllers/events/result_map_controller.js
- app/javascript/controllers/events/round_map_controller.js
- app/views/events/rounds/maps/_round_map.html.haml
> Round map - selecting groups

- app/javascript/redux/events/roundMap/designatedLane.js
- app/javascript/redux/events/roundMap/index.js
- app/javascript/redux/events/roundMap/loadRoundMap.js
- app/javascript/redux/events/roundMap/selectedResults.js
- app/javascript/redux/events/roundMap/showDlForResult.js
- app/presenters/events/rounds/show.rb
> Improve round map

- app/javascript/components/FlightProfiles/Charts/Tagbar/TerrainProfileTag.js
- app/javascript/components/FlightProfiles/Charts/Tagbar/TrackTag.js
- app/javascript/components/FlightProfiles/Charts/Tagbar/elements.js
- app/javascript/components/FlightProfiles/Charts/Tagbar/index.js
- app/javascript/redux/terrainProfiles/measurements/index.js
> Add delete button to terraine profile tag

- app/views/tracks/_show_track.html+mobile.haml
- app/views/tracks/_show_track.html.haml
Added new FAI window button on track view: `FAI window 2500-1500m`
Changed name of previous FAI window to `Old FAI window 3000-2000m`
Changes for mobile and web versions
> Adding new FAI window(2500-1500m)

- .circleci/config.yml
- Gemfile.lock
- app/models/point.rb
- app/parsers/track_parser.rb
- app/parsers/track_parser/columbus.rb
- app/parsers/track_parser/cyber_eye.rb
- app/parsers/track_parser/flysight.rb
- app/views/api/v1/tracks/points/show.json.jbuilder
- db/migrate/20210627083927_add_missing_flysight_fields_to_point.rb
- db/schema.rb
* horizontal accuracy
* vertical accuracy
* speed accuracy
* heading accuracy
* heading
* number of satellites visible
* gps fix
> Add previously ignored flysight fields

- app/javascript/api/hooks/speedSkydivingCompetitions/results.js
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Scoreboard/ResultModal/Charts.js
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Scoreboard/ResultModal/styles.module.scss
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Scoreboard/ResultModal/utils.js
> Display result, exit altitude and result window in result modal

- app/assets/stylesheets/_contributions.scss
- app/assets/stylesheets/_static_pages.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mobile/application.scss
- app/models/contribution.rb
- app/models/contribution/detail.rb
- app/models/contribution/summary.rb
- app/models/profile.rb
- app/presenters/landing_page.rb
- app/views/static_pages/_contributions.html.erb
- app/views/static_pages/index.html+mobile.haml
- app/views/static_pages/index.html.haml
- db/migrate/20211105133526_create_contributions.rb
- db/schema.rb
> Show contributions on main page

- app/controllers/assets/speed_skydiving_competitions/open_event_scoreboards_controller.rb
- app/controllers/assets/speed_skydiving_competitions/scoreboards_controller.rb
- app/controllers/assets/speed_skydiving_competitions/team_standigs_controller.rb
- app/javascript/api/speedSkydivingCompetitions/types.ts
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Downloads/index.tsx
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Downloads/styles.module.scss
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Header/Navbar.tsx
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/index.tsx
- app/models/concerns/competitor_country.rb
- app/models/event/competitor.rb
- app/models/speed_skydiving_competition/competitor.rb
- app/models/speed_skydiving_competition/scoreboard/standings.rb
- app/policies/speed_skydiving_competition_policy.rb
- app/views/api/v1/speed_skydiving_competitions/_speed_skydiving_competition.json.jbuilder
- app/views/assets/speed_skydiving_competitions/open_event_scoreboards/show.xml.builder
- app/views/assets/speed_skydiving_competitions/scoreboards/show.xml.builder
- app/views/events/competitors/_competitor_cells.html.haml
- app/views/events/scoreboards/show.xml.builder
- config/routes.rb
- spec/models/event/competitor_spec.rb
- spec/models/speed_skydiving_competition/competitor_spec.rb
> Open standings unloading to ISC website

- app/models/profile.rb
- app/models/track.rb
- app/models/virtual_competition/annual_top_score.rb
- app/models/virtual_competition/interval_top_score.rb
- app/models/virtual_competition/personal_top_score.rb
- app/models/virtual_competition/result.rb
- app/presenters/virtual_competitions/overall_presenter.rb
- app/presenters/virtual_competitions/period_page.rb
- app/presenters/virtual_competitions/summary.rb
- app/presenters/virtual_competitions/year_presenter.rb
- app/services/online_competitions_service.rb
- app/views/api/v1/profiles/show.json.jbuilder
- app/views/static_pages/_online_competitions_section.html.haml
- db/migrate/20220521074653_add_wind_cancelled_to_virtual_competition_results.rb
- db/migrate/20220521084208_update_interval_top_scores_to_version_2.rb
- db/migrate/20220521085320_update_annual_top_scores_to_version_5.rb
- db/migrate/20220521092055_update_personal_top_scores_to_version_5.rb
- db/schema.rb
- db/views/annual_top_scores_v05.sql
- db/views/interval_top_scores_v02.sql
- db/views/personal_top_scores_v05.sql
- spec/models/virtual_competition/annual_top_score_spec.rb
- spec/models/virtual_competition/interval_top_score_spec.rb
- spec/models/virtual_competition/personal_top_score_spec.rb
- spec/services/online_competitions_service_spec.rb
YAY! IT'S COMING! YAY!
/cc @FloKas
> Calculate wind cancelled result for online rankings

- app/javascript/api/users/common.ts
- app/javascript/api/users/useDeleteUserMutation.ts
- app/javascript/api/users/useUserQuery.ts
- app/javascript/components/Admin/Users/User/index.tsx
- app/javascript/components/Admin/Users/UsersIndex/index.tsx
- app/views/api/v1/users/_user.json.jbuilder
- spec/system/users/managing_spec.rb
- Add toast in case of success 
- redirect to previous url
- add specs
> Improve user deletion flow

- app/controllers/api/users/passwords_controller.rb
- app/javascript/api/users/index.ts
- app/javascript/api/users/useCreatePasswordMutation.ts
- app/javascript/api/users/useResetPasswordMutation.ts
- app/javascript/components/Users/ForgotPassword/index.tsx
- app/javascript/components/Users/NewPassword/index.tsx
- app/javascript/components/Users/NewPassword/validationSchema.ts
- app/javascript/components/Users/SignIn/index.tsx
- app/javascript/components/Users/index.tsx
- config/environments/test.rb
- config/locales/devise/en.yml
- config/locales/devise/fr.yml
- config/locales/devise/ru.yml
- config/locales/models/users/fr.yml
- config/locales/models/users/ru.yml
- config/routes.rb
- config/webpacker.yml
- spec/spec_helper.rb
- spec/system/users/reset_password_spec.rb
- Forgot password form
- Reset password form
- tests
> Forgot password flow

- app/controllers/assets/speed_skydiving_competitions/gps_recordings_controller.rb
- app/javascript/api/tracks/points.ts
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Downloads/index.tsx
- app/javascript/components/Events/SpeedSkydivingCompetition/Show/Scoreboard/ResultModal/utils.ts
- app/services/points_query.rb
- app/views/api/v1/tracks/points/show.json.jbuilder
- config/routes.rb
- spec/services/points_query/query_builder_spec.rb
- Display speed accuracy in place of vertical accuracy
- Download GPS recordings archive
> Speed skydiving - prepare to 1st category event

- lib/tasks/screenshot_results_speed.rake
Rake task to create screenshots from results in speed skydiving event
> Rake task to create screenshots from results in speed skydiving event

- .github/workflows/ssl_certificates.yml
> Fix SSL certificate renewal

- .github/workflows/ci.yml
- Gemfile.lock
- app/views/tournaments/_scoreboard.html.haml
- app/views/tournaments/qualifications/show.html.haml
- spec/models/event/result_spec.rb
Tournaments - quick fixes
- add surprise mode for qualifications table
- allow 4 rounds to be rendered on desktop
> Tournaments - quick fixes

- app/javascript/api/onlineRankings/common.ts
Make jumpsKind nullable in zod schema
> Make jumpsKind nullable in zod schema
